### ISSUE TITLE
miplevels are clamped to LDR when compressing to BC6H with auto-generate mipmaps

### ISSUE THREAD

**Issue by bkamo** [GameTechDev/Intel-Texture-Works-Plugin#10]
Hi,

It looks like if we compress HDR images to BC6H with auto-generate mipmaps turned on, miplevels other than 0 are clamped to LDR (or somewhat lower intensity value than miplevel 0). Please see the images attached.

We use export settings as below: output format is BC6H, and miplevels are auto-generated.

![image2016-2-25 16-32-32](https://cloud.githubusercontent.com/assets/14988752/13313904/d9a80850-dbe4-11e5-9761-98f5b16694b5.png)

Then if we load compressed BC6H dds and slightly darken miplevels, miplevels other than 0 are clamped to lower intensity.

![image2016-2-25 15-44-30](https://cloud.githubusercontent.com/assets/14988752/13313969/7f1bbd90-dbe5-11e5-87e5-88216022220c.png)

If we manually generate miplevels and compress to BC6H with them (using From Layers setting), the result is just as expected: miplevels are not clamped.
![image2016-2-25 16-36-49](https://cloud.githubusercontent.com/assets/14988752/13313923/07b733e2-dbe5-11e5-8e94-db2ed83b8f70.png)

Source image file (tif) and output file (dds) are attached below.
[test_bake6-pasted__FeMovableUV22SG-pSphere11.zip](https://github.com/GameTechDev/ITW-Beta-Test/files/146191/test_bake6-pasted__FeMovableUV22SG-pSphere11.zip)
[test_bake6-pasted__FeMovableUV22SG-pSphere11_encoded.zip](https://github.com/GameTechDev/ITW-Beta-Test/files/146192/test_bake6-pasted__FeMovableUV22SG-pSphere11_encoded.zip)

We are using Photoshop CS6 (64bit) and plug-in version is Beta1.

Thanks,
Jun

**Comment by jawilli312** [comment]
Thank you very much. Checking into this now.

**Comment by christop4D** [comment]
Hi
where did you load it back into and did the darken?
what did you use to darken it, can you post the steps in more detail?

thanks

**Comment by bkamo** [comment]
Hi,

To darken we lowered exposure value by using [exposure adjustment layers](https://helpx.adobe.com/photoshop/using/adjusting-hdr-exposure-toning.html).

We loaded the dds to Photoshop with miplevels on separate layers (as suggested by the plugin), then created exposure adjustment layers on top of them, and lowered exposure value.

Hope that helps,
Jun

**Comment by jawilli312** [comment]
Corrected in pending release 1.0.4
Thanks again.
