### ISSUE TITLE
Plugin will not load in Photoshop CC 2018

### ISSUE THREAD

**Issue by SgtGaToR** [GameTechDev/Intel-Texture-Works-Plugin#28]
I've tried saving plugin in different places in PS file directories but I always get the following error:
![intel texture work plugin error](https://user-images.githubusercontent.com/36717888/36514175-430b9e9e-1741-11e8-956b-b2fb3661984d.jpg)
I've tried the file formats folder within the plug-ins directory with same results.

Mark

Update: Guess it doesn't matter now downloaded GIMP 2.0 and its plugins and accomplished what I needed to do. Still would like to know why the plugin works w/CC 2016 but not latest version.

**Comment by zetaFairlight** [comment]
I'm going to try this plug-in on Adobe Photoshop right now, 
if it doesn't work then it's unfortunately practical for speed developments.

**Comment by DaveBookout-Intel** [comment]
the plugin must be save in the "Plug-ins\File Formats" directory. You may need to create the "File Formats" sub directory. the scripts should be copied to the "Presets\Scripts" directory.
