### ISSUE TITLE
Missing stuff / build impossible

### ISSUE THREAD

**Issue by JPatison** [GameTechDev/Intel-Texture-Works-Plugin#30]
As you can see in a "IntelTextureWorks.vcxproject" have build cmd line:
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">..\3rdParty\Intel\Tools\ispc -O2 "%(Filename).ispc" -o "$(IntDir)%(Filename).obj" -h "$(ProjectDir)%(Filename)_ispc.h" --arch=x86-64 --target=sse2,sse4,avx,avx2 --opt=fast-math</Command>

1. This project do not contain the folder "..\3rdParty\Intel\Tools". It has the "..\3rdParty\Intel\Source" only. And missing ispc.exe compiler.

**Comment by DaveBookout-Intel** [comment]
the ispc (Intel® Implicit SPMD Program Compiler) executable is required to build the *.ispc files for texcomp.dll.
see https://github.com/GameTechDev/ISPCTextureCompressor for building texcomp.dll
and https://github.com/ispc/ispc/releases for binaries to add to the ..\3rdParty\Intel\Tools\ directory. 

i've updated the build instructions to include ispc usage.
