### ISSUE TITLE
Cannot save default

### ISSUE THREAD

**Issue by thebestahri2019** [GameTechDev/Intel-Texture-Works-Plugin#34]
Preset save erorr
Can not save C:\Users\VIntel-last-used-.preset
不能存储为"C:\Users\周哈农会没看vn\... \Ayane.dds",因为Failed to Create Presets Directory。

**Comment by DaveBookout-Intel** [comment]
This does not appear to be an issue with photoshop or the plugin. resubmit with additional detail if  you believe this is a problem with the plugin.
