### ISSUE TITLE
Any possibility of this being ported for GIMP?

### ISSUE THREAD

**Issue by rjmxtechnology** [GameTechDev/Intel-Texture-Works-Plugin#37]
GIMP users would greatly benefit from such a tool with the ability to export into various dds formats (dx10+ dxt1) etc  (primarily suggesting this because I do work with the arkham games and many people cannot afford to purchase photoshop so this would be a great alternative) as it's free and open source. 

I lack the knowledge to do so myself and have been looking around for something that can do this, but haven't found anything. Thoughts?

**Comment by Hawkeye4040** [comment]
There are other [plugins](https://gimp-portable.com/gimp-dds-plugins/#:~:text=GIMP%20is%20unable%20to%20create/convert/open%20files%20in%20DDS,files,%20optionally%20using%20DirectX%20texture%20compression%20(DXT)%20.) for DDS on Gimp already.

**Comment by DaveBookout-Intel** [comment]
additional plugin support is outside the scope of this project. the existing plugins could potentially be extended to support additional formats using: https://github.com/GameTechDev/ISPCTextureCompressor.
