### ISSUE TITLE
E.T.A for the Mac support?

### ISSUE THREAD

**Issue by vicentecarrodev** [GameTechDev/Intel-Texture-Works-Plugin#5]
I know Mac is not supported right now but is there an ETA for it? Even a roughly estimation could help.
note: How can I add labels to the message?

**Comment by jawilli312** [comment]
Mac support would depend on demand. Your's is the first request thus far

**Comment by jawilli312** [comment]
The plugin has been architected in anticipation of eventual Mac support. Actual implementation would depend on demand. Your's is the first request thus far. Thank you.

**Comment by vicentecarrodev** [comment]
Thank you.

**Comment by SamusAranX** [comment]
Consider this to be the second request then. 
Having to boot into my Windows partition that's normally only used for games, not work, is really annoying.

**Comment by fnordware** [comment]
No, https://github.com/fnordware/AdobeDDS does not have cubemap support, although it looks like a checkbox could be added to call this function in crnlib:

https://github.com/BinomialLLC/crunch/blob/master/crnlib/crn_mipmapped_texture.cpp#L2401

**Comment by bitinn** [comment]
@fnordware thx for clearing that up!

For people wondering about cubemap though, https://github.com/dariomanesku/cmftStudio is a much easier choice :)

**Comment by fnordware** [comment]
OK, I added cube map support to https://github.com/fnordware/AdobeDDS

**Comment by AnalogMan151** [comment]
I would also like macOS support. I've taken up developing with Nintendo Switch and currently use this plugin on Windows but my primary machine is macOS and it would be great to have this amazing plugin available for both.

**Comment by DaveBookout-Intel** [comment]
Sorry, we do not have plans to support Mac support, but we will keep it in mind for future updates.
